bids:
  dataset_name: bids_autoconv
  patches:
  - '{data_pipeline_path}/patches/hirni_heuristic.patch'
  default_procedure_dir: code/procedures
  procedure_python_template: templates/procedure_template.py
  procedure_shell_template: templates/procedure_template.sh
  rule_dir: code/costum_rules
  rule_name: custom_rules.py
  rule_template: templates/cutom_rule_template.py
  working_dir: working/dir/path
rsync:
  dest:
    path: path2
  src:
    host: my_host
    path: path1
    user: my_user
subject_file: subjects.json
