subject_file: subjects.json
rsync:
    src:
        user: my_user
        host: my_host
        path: path1
    dest:
        #user:
        #host:
        path: path2
bids:
    working_dir: working/dir/path
    dataset_name: bids_autoconv
    patches:
        - "/path/to/patch/hirni_heuristic.patch"
