subject_file: subjects.json
rsync:
    src:
        user: my_user
        host: my_host
        path: path1
    dest:
        #user:
        #host:
        path: path2
bids:
    working_dir: working/dir/path
    dataset_name: bids_autoconv
    patches:
        # Either the full path to the patch or use {data_pipeline_path}
        # to refer to the current path of the data-pipeline source code
        - "{data_pipeline_path}/patches/hirni_heuristic.patch"
