bids_conversion:
    source:
        dataset_name: sourcedata
        setup_procedure: cfg_hirni
        patches:
            # Either the full path to the patch or use {data_pipeline_path}
            # to refer to the current path of the data-pipeline source code
            - "{data_pipeline_path}/patches/hirni_heuristic.patch"
        # Adds a gitignore file with the most commen defaults into the datasets
        add_gitignore: true
    bids:
        dataset_name: bids
        setup_procedure: cfg_bids
#        patches:
#            # Either the full path to the patch or use {data_pipeline_path}
#            # to refer to the current path of the data-pipeline source code
        add_gitignore: true

    config_acqid: bids_rule_config
    # hirni will remove underscores form the anon_subject entry
    # e.g. bids_config -> bidsconfig
    config_anon_subject: bidsconfig

    default_procedure_dir: code/procedures
    procedure_python_template: templates/procedure_template.py
    procedure_shell_template: templates/procedure_template.sh

    rule_dir: code/custom_rules
    rule_name: custom_rules.py
    rule_template: templates/custom_rules_template.py

    validator_container_name: "bids-validator.simg"
    validator_image_url: "docker://bids/validator"
    validator_config_template: templates/bids-validator-config_template.json
    container_dir: "code/containers"

rsync:
    src:
        user: my_user
        host: my_host
        path: path1
    dest:
        #user:
        #host:
        path: path2

subject_file: subjects.json